### ISSUE TITLE
Initial Implementation bucket list

### ISSUE THREAD

**Issue by LuisBoto** [MasterCloudApps-Projects/patterned-nodeJS#2]
This is a list of all tasks defined for the implementation of the initial version. Tasks may be added or removed as we see fit.

Development is carried on the [initialImplementation](https://github.com/MasterCloudApps-Projects/patterned-nodeJS/tree/initialImplementation) branch.

## Top priority
- [x] **Fix pawn movement bug when using mementos** 
      _Pawns will recalculate position and direction upon memento usage, so advanced ones will move in the wrong direction_

### Tasks

- [x] Definition of game module
- [x] Usage of an UUID generated on frontend to identify specific games
- [x] Creation of a board builder
- [x] Definition of a Board module with top level operations (piece movement etc)
- [x] Creation of piece factories
- [x] Creation of piece movement strategies modules
  - [x] Pawn movement
    - [x] Pawn becomes queen at the end of the board
  - [x] Rook movement
  - [x] Bishop movement
  - [x] Horse movement
  - [x] Queen movement as a composite of rook & bishop
  - [x] King movement ~~(missing diagonal movements as of now)~~
- [x] Creation of simple CPUplayer which makes a random movement
- [x] Improve error message handling
- [x] Adding logic to the rules of the game:
  - [x] Evaluate _check_ (could use getAllCoordinatesThreatenedByColor on board.js)
  - [x] Force movement of the king in _check_ player (player & cpu player)
  - [x] Evaluate _checkmate_ -> end of game

-- Extra: 
- [x] Memento to undo/redo movements. (jmrv)
  - (Experimental) Flyweight to avoid using strings as mementos

-- (Potential next version) 
Level CPU Player: 
  - Level 0 - random movement
  - Level 1 - evaluate & choose kill movement if is possible
  - Level 2 - evaluate & choose check movement

**Comment by LuisBoto** [comment]
Created a game js module. Complementarily also created stub files for the board & boardBuilder modules, which are basically lacking all but minimal functionality at the moment.

**Comment by LuisBoto** [comment]
Completed boardBuilder module, most notably it now supports custom board layouts via string parameter. Created a piece factory 'superclass' as well as two child classes, blackPiece and whitePiece factories which are used on the board builder.

Which factory is used for each piece (on the board builder) is decided via a dictionary imported from the factory superclass, however as of now pieces are just short strings instead of proper objects. I found inheritance to be somewhat challenging to mimic using modules so any review or improvement on pieceFactory.js is welcome 👐🤖

**Comment by lmorente** [comment]
Added in the 'game' module the operations for the movement of the player's pieces and the cpu player. For this purpose, the movement of the white pieces is limited to the player. 
- Invalid movement validation by part color is added (if the player moves a white piece, the move is performed and the random move of the player cpu is generated, otherwise the board is returned unchanged).

**Comment by lmorente** [comment]
The cpu player is created. The cpu player randomly moves black pieces (moves only black pieces to empty squares). 
//TODO: the rest of the movements will be developed as functionality progresses.

**Comment by lmorente** [comment]
The possible moves of the pawns are added. This code is not implemented in the game logic, it can be used in the future when this functionality is added. It can be used for the possible moves of the cpu player and the validation of player moves.

**Comment by LuisBoto** [comment]
Just created a Piece.js module, as well as integrated piece objects with their own functions into the movement and board codes. Also defined a 'superclass' module to be used with movement strategies. Both of these things resulted in a big refactor, where all functionality on utils.js was reworked and absorbed into movement.js. 

A lot of the code on pawnMovement.js was refactored too to take full advantage of the piece responsabilities and the super class methods.

Small tweaks on board and cpuPlayer allowed integration of movement logic with no problems. For now, since only pawn movement logic exists, all other pieces just allow all movements.

**Comment by LuisBoto** [comment]
Added horseMovement.js (which turned out pretty short code-wise) and made error messages from movements propagate and get back to front end. This however feels a bit patchy, maybe we should think of a pattern to handle messages.

**Comment by LuisBoto** [comment]
Update for today:

- Renamed longStrokePiece.js to straightLineMovement.js, also fixed a small bug that allowed pieces to jump opposite color pieces.
- Added a function on board.js to get all squares threatened by pieces of a certain color. This could be used to implement checks and checkmates.
- Added doAfterMovement() on piece.js and movements to be called after a successful board movement. It's mainly used by the pawn to check whether it should turn into a queen but maybe other pieces got some use for it too (checkmates maybe idk).
- Refactored pieceFactory.js piece-specific-functions to some sort of 'decorator' functions now on piece.js. Again this mainly benefits the pawn to queen functionality, but it's overall better design.
- Got move() out of movement strategies and into movement.js. It's now a simple check on whether possible movements include the destination across all pieces.

@joseramosvalderrama is now onto developing a board memento and improving the error message system 🔥🥳

**Comment by joseramosvalderrama** [comment]
Undo/Redo functionality has been implemented using memento pattern.

**Comment by joseramosvalderrama** [comment]
- The data that is sended from backend to frontend has now a common interface.
- The responsability of doing requests to the backend is now encapsulated in one function that makes use of fetch api.

**Comment by LuisBoto** [comment]
Refactored a bit the movements package. Added composite pattern on queenMovement, and coordinate indexes are now visible on front end.
